apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-dynamic
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-csi

---
apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
  namespace: default
spec:
  containers:
  - name: simple-container
    image: nginx
    volumeMounts:
    - name: data-volume
      mountPath: "/usr/share/nginx/html"
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: pvc-nfs-dynamic